import type { AppNotification, AuditLog, CheckIn, Cycle, Goal, User } from "./types";

export const seedUsers: User[] = [
  {
    id: "u-admin",
    name: "Priya Sharma",
    email: "admin@goalsync.com",
    role: "admin",
    department: "Human Resources",
    designation: "Head of People Ops",
    managerId: null,
    createdAt: "2025-01-10",
  },
  {
    id: "u-mgr",
    name: "Daniel Hayes",
    email: "manager@goalsync.com",
    role: "manager",
    department: "Engineering",
    designation: "Engineering Manager",
    managerId: "u-admin",
    createdAt: "2025-01-12",
  },
  {
    id: "u-mgr2",
    name: "Aisha Khan",
    email: "aisha@goalsync.com",
    role: "manager",
    department: "Product",
    designation: "Director of Product",
    managerId: "u-admin",
    createdAt: "2025-01-12",
  },
  {
    id: "u-emp",
    name: "Jordan Lee",
    email: "employee@goalsync.com",
    role: "employee",
    department: "Engineering",
    designation: "Senior Software Engineer",
    managerId: "u-mgr",
    createdAt: "2025-02-01",
  },
  {
    id: "u-emp2",
    name: "Maya Patel",
    email: "maya@goalsync.com",
    role: "employee",
    department: "Engineering",
    designation: "Frontend Engineer",
    managerId: "u-mgr",
    createdAt: "2025-02-04",
  },
  {
    id: "u-emp3",
    name: "Carlos Rivera",
    email: "carlos@goalsync.com",
    role: "employee",
    department: "Engineering",
    designation: "Backend Engineer",
    managerId: "u-mgr",
    createdAt: "2025-02-05",
  },
  {
    id: "u-emp4",
    name: "Sara Lin",
    email: "sara@goalsync.com",
    role: "employee",
    department: "Product",
    designation: "Product Manager",
    managerId: "u-mgr2",
    createdAt: "2025-02-06",
  },
  {
    id: "u-emp5",
    name: "Tom Becker",
    email: "tom@goalsync.com",
    role: "employee",
    department: "Product",
    designation: "Designer",
    managerId: "u-mgr2",
    createdAt: "2025-02-08",
  },
];

const today = new Date().toISOString();

export const seedGoals: Goal[] = [
  {
    id: "g-1",
    employeeId: "u-emp",
    thrustArea: "Product Excellence",
    title: "Ship payments v2 with 99.9% uptime",
    description: "Lead the rollout of v2 payments stack across 3 regions.",
    uomType: "percentage",
    target: 99.9,
    achievement: 99.7,
    weightage: 30,
    progressPercentage: 92,
    status: "approved",
    progressStatus: "on-track",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "g-2",
    employeeId: "u-emp",
    thrustArea: "Customer Success",
    title: "Reduce P1 incidents by 40%",
    description: "Drive root-cause analysis and prevention.",
    uomType: "percentage",
    target: 40,
    achievement: 28,
    weightage: 25,
    progressPercentage: 70,
    status: "approved",
    progressStatus: "on-track",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "g-3",
    employeeId: "u-emp",
    thrustArea: "People & Culture",
    title: "Mentor 3 junior engineers",
    description: "Quarterly mentorship plan + reviews.",
    uomType: "numeric",
    target: 3,
    achievement: 2,
    weightage: 20,
    progressPercentage: 66,
    status: "approved",
    progressStatus: "on-track",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "g-4",
    employeeId: "u-emp",
    thrustArea: "Innovation",
    title: "Launch internal AI assistant",
    description: "Pilot for engineering org.",
    uomType: "timeline",
    target: 1,
    achievement: 0,
    weightage: 25,
    progressPercentage: 35,
    status: "approved",
    progressStatus: "at-risk",
    isLocked: true,
    isShared: true,
    sharedGoalId: "sg-1",
    createdAt: today,
    updatedAt: today,
  },

  {
    id: "g-5",
    employeeId: "u-emp2",
    thrustArea: "Product Excellence",
    title: "Migrate UI to design system v3",
    description: "",
    uomType: "percentage",
    target: 100,
    achievement: 65,
    weightage: 40,
    progressPercentage: 65,
    status: "submitted",
    progressStatus: "on-track",
    isLocked: false,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "g-6",
    employeeId: "u-emp2",
    thrustArea: "Quality",
    title: "Achieve 90% test coverage",
    description: "",
    uomType: "percentage",
    target: 90,
    achievement: 78,
    weightage: 30,
    progressPercentage: 86,
    status: "submitted",
    progressStatus: "on-track",
    isLocked: false,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "g-7",
    employeeId: "u-emp2",
    thrustArea: "Innovation",
    title: "Launch internal AI assistant",
    description: "Shared org goal.",
    uomType: "timeline",
    target: 1,
    achievement: 0,
    weightage: 30,
    progressPercentage: 35,
    status: "submitted",
    progressStatus: "at-risk",
    isLocked: false,
    isShared: true,
    sharedGoalId: "sg-1",
    createdAt: today,
    updatedAt: today,
  },

  {
    id: "g-8",
    employeeId: "u-emp3",
    thrustArea: "Reliability",
    title: "Cut API p95 latency to <120ms",
    description: "",
    uomType: "numeric",
    target: 120,
    achievement: 145,
    weightage: 50,
    progressPercentage: 45,
    status: "approved",
    progressStatus: "at-risk",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "g-9",
    employeeId: "u-emp3",
    thrustArea: "People & Culture",
    title: "Zero security incidents",
    description: "",
    uomType: "zero-based",
    target: 0,
    achievement: 0,
    weightage: 50,
    progressPercentage: 100,
    status: "approved",
    progressStatus: "completed",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },

  {
    id: "g-10",
    employeeId: "u-emp4",
    thrustArea: "Growth",
    title: "Increase activation rate by 15%",
    description: "",
    uomType: "percentage",
    target: 15,
    achievement: 9,
    weightage: 60,
    progressPercentage: 60,
    status: "approved",
    progressStatus: "on-track",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "g-11",
    employeeId: "u-emp4",
    thrustArea: "Customer Success",
    title: "Run 12 customer interviews",
    description: "",
    uomType: "numeric",
    target: 12,
    achievement: 14,
    weightage: 40,
    progressPercentage: 100,
    status: "approved",
    progressStatus: "completed",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },

  {
    id: "g-12",
    employeeId: "u-emp5",
    thrustArea: "Design System",
    title: "Ship 8 new components",
    description: "",
    uomType: "numeric",
    target: 8,
    achievement: 5,
    weightage: 70,
    progressPercentage: 62,
    status: "approved",
    progressStatus: "on-track",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "g-13",
    employeeId: "u-emp5",
    thrustArea: "People & Culture",
    title: "Run 4 design crits",
    description: "",
    uomType: "numeric",
    target: 4,
    achievement: 3,
    weightage: 30,
    progressPercentage: 75,
    status: "approved",
    progressStatus: "on-track",
    isLocked: true,
    isShared: false,
    createdAt: today,
    updatedAt: today,
  },
];

export const seedCheckIns: CheckIn[] = [
  {
    id: "c-1",
    goalId: "g-1",
    quarter: "Q1",
    plannedTarget: 99.5,
    actualAchievement: 99.6,
    status: "on-track",
    managerComment: "Great progress, keep the momentum.",
    checkinDate: "2025-07-20",
  },
  {
    id: "c-2",
    goalId: "g-1",
    quarter: "Q2",
    plannedTarget: 99.7,
    actualAchievement: 99.7,
    status: "on-track",
    checkinDate: "2025-10-15",
  },
  {
    id: "c-3",
    goalId: "g-2",
    quarter: "Q1",
    plannedTarget: 15,
    actualAchievement: 12,
    status: "on-track",
    checkinDate: "2025-07-20",
  },
  {
    id: "c-4",
    goalId: "g-4",
    quarter: "Q1",
    plannedTarget: 0.25,
    actualAchievement: 0.1,
    status: "at-risk",
    managerComment: "Schedule a sync to unblock.",
    checkinDate: "2025-07-22",
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "n-1",
    recipientId: "u-mgr",
    type: "submit",
    title: "Maya Patel submitted goals",
    message: "3 goals ready for your review.",
    read: false,
    createdAt: today,
  },
  {
    id: "n-2",
    recipientId: "u-emp",
    type: "approve",
    title: "Your goals were approved",
    message: "Daniel Hayes approved 4 goals for FY26.",
    read: false,
    createdAt: today,
  },
  {
    id: "n-3",
    recipientId: "u-emp",
    type: "reminder",
    title: "Q2 check-in due",
    message: "Submit your Q2 update by Oct 15.",
    read: true,
    createdAt: today,
  },
  {
    id: "n-4",
    recipientId: "u-admin",
    type: "escalation",
    title: "Pending approval > 5 days",
    message: "Aisha Khan has 2 pending approvals.",
    read: false,
    createdAt: today,
  },
];

export const seedAudit: AuditLog[] = [
  {
    id: "a-1",
    userId: "u-mgr",
    actionType: "APPROVE",
    moduleName: "Goals",
    oldValue: "submitted",
    newValue: "approved",
    timestamp: today,
  },
  {
    id: "a-2",
    userId: "u-emp",
    actionType: "UPDATE",
    moduleName: "Goals",
    oldValue: "achievement=99.5",
    newValue: "achievement=99.7",
    timestamp: today,
  },
  {
    id: "a-3",
    userId: "u-admin",
    actionType: "UNLOCK",
    moduleName: "Goals",
    oldValue: "locked",
    newValue: "unlocked",
    timestamp: today,
  },
  {
    id: "a-4",
    userId: "u-admin",
    actionType: "CREATE",
    moduleName: "Shared Goals",
    newValue: "Launch internal AI assistant",
    timestamp: today,
  },
];

export const seedCycles: Cycle[] = [
  {
    id: "cy-1",
    phaseName: "Goal Setting",
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    status: "closed",
  },
  {
    id: "cy-2",
    phaseName: "Q1 Check-in",
    startDate: "2025-07-01",
    endDate: "2025-07-31",
    status: "closed",
  },
  {
    id: "cy-3",
    phaseName: "Q2 Check-in",
    startDate: "2025-10-01",
    endDate: "2025-10-31",
    status: "closed",
  },
  {
    id: "cy-4",
    phaseName: "Q3 Check-in",
    startDate: "2026-01-01",
    endDate: "2026-01-31",
    status: "closed",
  },
  {
    id: "cy-5",
    phaseName: "Annual Review",
    startDate: "2026-03-15",
    endDate: "2026-04-30",
    status: "active",
  },
];

export const thrustAreas = [
  "Product Excellence",
  "Customer Success",
  "Growth",
  "Reliability",
  "Innovation",
  "People & Culture",
  "Quality",
  "Design System",
];
